### ISSUE TITLE
[help]: v1.0编译报错，退到v0.9编译烧写启动显示版本是v1.0

### ISSUE THREAD

**Issue by superbinary-code** [kendryte/k230_sdk#11]
### Help

v1.0编译报错：
---- NO ENCRYPTION + HASH-256 -----
the encryption type:  0
mesg_hash:  b'e886bbf77d7b3efdc6a0fdb2cfeef3b7b567f5c4cbe1bd68c98e56583701aedf'
/home/mike/k230/v1.0/k230_sdk/tools/genimage: error while loading shared libraries: libconfuse.so.2: cannot open shared object file: No such file or directory

git checkout 41f7d1c 到v0.9，再编译成功，但是启动的时候小核心启动log显示是v1.0版本

**Comment by wuwentao** [comment]
@superbinary-code 
最新的v1.0版本docker image推送ghcr.io报错了，已修复并上传。
请拉取最新的编译环境即可解决。或者基于文档repo中的说明，自行编译docker镜像使用。

```
docker pull ghcr.io/kendryte/k230_sdk:latest
```

**Comment by superbinary-code** [comment]
验证ok，谢谢

**Comment by wuwentao** [comment]
fixed with latest docker image
