### ISSUE TITLE
uart1发送，uart2接收，运行./sample_canaan_uart_tx.elf 结果不符预期

### ISSUE THREAD

**Issue by superbinary-code** [kendryte/k230_sdk#12]
### What happened

<img width="960" alt="1" src="https://github.com/kendryte/k230_sdk/assets/59078456/2bd61263-9fae-4f5a-a08b-b9e965fde9e9">

### Reproduction steps

连接J12 pin5 & pin7 ,运行./sample_canaan_uart_tx.elf

### Hardware board

k230 evb board

### Software version

v1.0

### Bug frequency

必现

**Comment by fanjuntao637** [comment]
您好，sample_canaan_uart_tx.elf使用了两路串口，数据从uart4发出，从uart2接收，内部测试时同时使用了两块evb板。
我们也注意到这个demo的设计有些不友好的地方，我们将会在后续版本中对此进行优化，请您关注k230_sdk的版本更新。

**Comment by zhangxiaojingCAN** [comment]
close the issue, You can reopen it if any further question. Thx
