### ISSUE TITLE
[other]: README.md的图片有缺失

### ISSUE THREAD

**Issue by bonuschild** [kendryte/k230_sdk#14]
### Other

两款开发板的图片有白边，没法看准确的器件标号。

**Comment by LearnigF** [comment]
hello 目前可以手动在readme的文本中使用图片的原始链接查看
https://kendryte-download.canaan-creative.com/k230/downloads/doc_images/k230_unsip_board.png
https://kendryte-download.canaan-creative.com/k230/downloads/doc_images/k230_canmv/k230_unsip_canmv_board.png

**Comment by bonuschild** [comment]
好嘞，可以看到现在，谢谢！
        
    
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年10月16日 11:35
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [kendryte/k230_sdk] [other]: README.md的图片有缺失 (Issue #14)
        
      
    
  

hello 目前可以手动在readme的文本中使用图片的原始链接查看
https://kendryte-download.canaan-creative.com/k230/downloads/doc_images/k230_unsip_board.png
https://kendryte-download.canaan-creative.com/k230/downloads/doc_images/k230_canmv/k230_unsip_canmv_board.png
