### ISSUE TITLE
[help]: does CanMV-k230 have SPI flash

### ISSUE THREAD

**Issue by yf13** [kendryte/k230_sdk#17]
### Help

The `k230_canmv.dts` defines `spi-flash@0` but Linux dmesg complains that: 

 `[    1.960118] spi-nor: probe of spi0.0 failed with error -2 ` .

May I confirm whether the board has SPI flash or not?

**Comment by chenhb3** [comment]
CanMV-k230 board  don't have spi flash

**Comment by yf13** [comment]
Then maybe we should disable/remove the `&spi0` node in `k230_canmv.dts` of Linux source tree?
