### ISSUE TITLE
[other]: source of `tools/genimage`

### ISSUE THREAD

**Issue by yf13** [kendryte/k230_sdk#18]
### Other

It seems that v1.0 added binary `tools/genimage` command and dropped the original `tools/gen_image.sh` script. 
Can you teach if this tool is the same as [this one](https://github.com/pengutronix/genimage)? 
if so, maybe we don't need check-in the binary file but reuse the one generated in `buildroot-ext/host/bin` folder?

**Comment by yf13** [comment]
It looks like [this tool](https://github.com/pengutronix/genimage), so close the question for now.

**Comment by yf13** [comment]
It looks like [this tool](https://github.com/pengutronix/genimage), so close for now.

**Comment by wangjianxin-canaan** [comment]
> ### Other
> It seems that v1.0 added binary `tools/genimage` command and dropped the original `tools/gen_image.sh` script. Can you teach if this tool is the same as [this one](https://github.com/pengutronix/genimage)? if so, maybe we don't need check-in the binary file but reuse the one generated in `buildroot-ext/host/bin` folder?

yes, tools/genimage is the same as https://github.com/pengutronix/genimage.do not need check the binary file.
The reason for this change is that  when  only rtt  system  can uncompile buildroot.

**Comment by yf13** [comment]
@zhangxiaojingCAN thanks for the explanations. Maybe we can also consider to put the `genimage` command as a part of the  Docker image so that we can start building RTOS stuffs without having to go through build root.
