### ISSUE TITLE
[help]: audio recorded on CanMV-k230 can't be heard

### ISSUE THREAD

**Issue by yf13** [kendryte/k230_sdk#19]
### Help

I can capture .wav via `app/sample_audio.elf -type 1 -filename pdm.wav`  from big core console, but when playing it on Ubuntu host with `play pdm.wav` command, nothing can be heard. Meanwhile, I can hear other audio playing correctly on Ubuntu so it is might not be my host settings issue.

**Comment by gh-sxp** [comment]
CanMV-k230 does not support pdm and can be replaced with i2s.You can capture .wav via app/sample_audio.elf -type 0 -enablecodec 1 bitwidth 16 -filename i2s.wav from big core console.

**Comment by gh-sxp** [comment]
For more detailed usage methods, please refer to the documentation:
https://github.com/kendryte/k230_docs/blob/main/zh/01_software/board/examples/K230_SDK_CanMV_Board_Demo%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97.md

**Comment by yf13** [comment]
@gh-sxp thanks for the information, however, `-type 0` still doesn't work here.
Here I did use any external mircophone when recording as I assume there is one microphone on CanMV board, is this correct?

**Comment by gh-sxp** [comment]
hi，There is no microphone on the CanMV board. When recording audio, you can insert headphones to try and see if you can record the sound input from the headphones. If you still cannot record sound, you can plug and unplug the headphones during the recording process.

**Comment by yf13** [comment]
Thanks, I see now. I thought that `B4013AM` MIC is mounted. After retrying with a headphone with MIC, I can hear the recordings now.  

May I ask  if the `B4013AM` is also mounted, which option should we use to record via it? Since in this case,  there will be two MICs available on the board.

**Comment by yf13** [comment]
Thanks! I thought that `B4013AM` MIC is mounted. After retrying a headphone w/ mic , I can hear it now.  

May I ask  if the `B4013AM` is also mounted, which option should we use to record via it? Since in this case,  there will be two MICs available.

**Comment by gh-sxp** [comment]
If two mics are available and you only want to record one, you can specify the parameters channels and monochannel.
Record microphone audio using the following command: app/sample_audio.elf - type 0 -enablecodec 1 -bitwidth 16 -channels 1 -monochannel 0 -filename mic.wav
Record headphone audio using the following command: app/sample_audio.elf  -type 0 -enablecodec 1 -bitwidth 16 -channels 1 -monochannel 1 -filename headphone.wav

**Comment by yf13** [comment]
@gh-sxp thanks for the information.
