### ISSUE TITLE
[Bug]: can't build all with the default config

### ISSUE THREAD

**Issue by gasbytes** [kendryte/k230_sdk#22]
### What happened

basically i wanted to build from scratch the sdk with the usual command described by the README, using the rv32 as linux kernel for buildroot:

`make CONF=k230_evb_defconfig BR2_LINUX_KERNEL_DEFCONFIG=rv32`

and it fails when trying to build the `mpp-apps` target, here are the logs:
https://pastebin.com/ujNpbDJR

### Reproduction steps

enter the docker environment:
`docker run -u root -it -v $(pwd):$(pwd) -v $(pwd)/toolchain:/opt/toolchain -w $(pwd) k230_docker /bin/bash`

run the build all make command with the k230_evb_defconfig:
`make` `CONF=k230_evb_defconfig`

### Hardware board

k230 evb board

### Software version

v1.0.2

### Bug frequency

everytime i try to build all the sdk to produce the images

**Comment by wangjianxin-canaan** [comment]
change linux defconfig please change CONFIG_LINUX_DEFCONFIG  ,

example : configs/k230_canmv_defconfig    :  CONFIG_LINUX_DEFCONFIG="k230_canmv"  
                configs/k230_canmv_only_linux_defconfig :  CONFIG_LINUX_DEFCONFIG="k230_evb_linux_enable_vector"

**Comment by wangjianxin-canaan** [comment]
please check src/big/mpp/userapps/sample/sample_cipher/sample_aes/sample_aes.c   file , this file  is modified by mistake ?
Re-download a new code, can compile successfully?

**Comment by gasbytes** [comment]
yup, i did a fresh clone on the /tmp and did the whole setup from scratch, and it works fine again, thank you
