### ISSUE TITLE
[help]: micropython status on CanMV-k230

### ISSUE THREAD

**Issue by yf13** [kendryte/k230_sdk#23]
### Help

What is the status of micro python on CanMV-k230 device? It seems that SDK v1.0.1 doesn't have it yet?

**Comment by wuwentao** [comment]
please check the detail with below repo:

[https://github.com/kendryte/k230_canmv](https://github.com/kendryte/k230_canmv)

the docs can be found at: 
[https://github.com/kendryte/k230_canmv_docs/tree/main/zh/01_software](https://github.com/kendryte/k230_canmv_docs/tree/main/zh/01_software)

**Comment by yf13** [comment]
thanks!
