### ISSUE TITLE
[other]: output folder design suggestion

### ISSUE THREAD

**Issue by yf13** [kendryte/k230_sdk#27]
### Other

It is reasonable to have `src/common` folder, but having `output/.../common` folder seems confusing as no artifacts are common to both cores, they are either for big-core or for little-core.

Maybe we should revise the output folder design so that to replace `common/` with `big/opensbi`, `big/cdk`,  `little/opensbi`,  `little/cdk` respectively?

**Comment by LearnigF** [comment]
Thank you for your offer.
At present, the makefile in cdk is not perfectly written, and it doesn't include the output generated by the compiled product, which we will improve later.
In addition, the little and big in the common is mainly for the convenience of customers to easily get the compilation products of small and big cores.

**Comment by yf13** [comment]
okay, we can close this ticket.
