### ISSUE TITLE
[Bug]: bsp : k230_canmv , by docker build  make CONF=k230_canmv_defconfig error

### ISSUE THREAD

**Issue by flightxgf** [kendryte/k230_sdk#29]
### What happened

Makefile.am: installing './depcomp'
>>> host-libffi 3.3 Patching libtool
patching file /root/workspace/k230/k230_sdk/output/k230_canmv_defconfig/little/buildroot-ext/build/host-libffi-3.3/ltmain.sh
Hunk #1 succeeded at 2694 (offset 7 lines).
Hunk #2 succeeded at 4284 (offset 7 lines).
Hunk #3 succeeded at 6579 (offset 25 lines).
Hunk #4 succeeded at 6589 (offset 25 lines).
Hunk #5 succeeded at 6882 (offset 25 lines).
Hunk #6 succeeded at 7174 (offset 25 lines).
Hunk #7 succeeded at 8140 (offset 28 lines).
Hunk #8 succeeded at 10769 (offset 59 lines).
(cd /root/workspace/k230/k230_sdk/output/k230_canmv_defconfig/little/buildroot-ext/build/host-libffi-3.3/ && rm -rf config.cache; PATH="/root/workspace/k230/k230_sdk/output/k230_canmv_defconfig/little/buildroot-ext/host/bin:/root/workspace/k230/k230_sdk/output/k230_canmv_defconfig/little/buildroot-ext/host/sbin:/opt/toolchain/Xuantie-900-gcc-linux-5.10.4-glibc-x86_64-V2.6.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/toolchain/riscv64-linux-musleabi_for_x86_64-pc-linux-gnu/bin:/opt/toolchain/Xuantie-900-gcc-linux-5.10.4-glibc-x86_64-V2.6.0/bin" PKG_CONFIG="/root/workspace/k230/k230_sdk/output/k230_canmv_defconfig/little/buildroot-ext/host/bin/pkg-config" PKG_CONFIG_SYSROOT_DIR="/" PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 PKG_CONFIG_LIBDIR="/root/workspace/k230/k230_sdk/output/k230_canmv_defconfig/little/buildroot-ext/host/lib/pkgconfig:/root/workspace/k230/k230_sdk/output/k230_canmv_defconfig/little/buildroot-ext/host/share/pkgconfig" AR="/usr/bin/ar" AS="/usr/bin/as" LD="/usr/bin/ld" NM="/usr/bin/nm" CC="/usr/bin/gcc" GCC="/usr/bin/gcc" CXX="/usr/bin/g++" CPP="/usr/bin/cpp" OBJCOPY="/usr/bin/objcopy" RANLIB="/usr/bin/ranlib" CPPFLAGS="-I/root/workspace/k230/k230_sdk/output/k230_canmv_defconfig/little/buildroot-ext/host/include" CFLAGS="-O2 -I/root/workspace/k230/k230_sdk/output/k230_canmv_defconfig/little/buildroot-ext/host/include" CXXFLAGS="-O2 -I/root/workspace/k230/k230_sdk/output/k230_canmv_defconfig/little/buildroot-ext/host/include" LDFLAGS="-L/root/workspace/k230/k230_sdk/output/k230_canmv_defconfig/little/buildroot-ext/host/lib -Wl,-rpath,/root/workspace/k230/k230_sdk/output/k230_canmv_defconfig/little/buildroot-ext/host/lib" INTLTOOL_PERL=/usr/bin/perl CFLAGS="-O2 -I/root/workspace/k230/k230_sdk/output/k230_canmv_defconfig/little/buildroot-ext/host/include" LDFLAGS="-L/root/workspace/k230/k230_sdk/output/k230_canmv_defconfig/little/buildroot-ext/host/lib -Wl,-rpath,/root/workspace/k230/k230_sdk/output/k230_canmv_defconfig/little/buildroot-ext/host/lib"  CONFIG_SITE=/dev/null ./configure --prefix="/root/workspace/k230/k230_sdk/output/k230_canmv_defconfig/little/buildroot-ext/host" --sysconfdir="/root/workspace/k230/k230_sdk/output/k230_canmv_defconfig/little/buildroot-ext/host/etc" --localstatedir="/root/workspace/k230/k230_sdk/output/k230_canmv_defconfig/little/buildroot-ext/host/var" --enable-shared --disable-static --disable-gtk-doc --disable-gtk-doc-html --disable-doc --disable-docs --disable-documentation --disable-debug --with-xmlto=no --with-fop=no --disable-nls --disable-dependency-tracking   )
configure: WARNING: unrecognized options: --disable-gtk-doc, --disable-gtk-doc-html, --disable-doc, --disable-documentation, --with-xmlto, --with-fop, --disable-nls
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
continue configure in default builddir "./x86_64-pc-linux-gnu"
....exec /bin/bash .././configure "--srcdir=.." "--enable-builddir=x86_64-pc-linux-gnu" "linux
gnu"
configure: WARNING: unrecognized options: --disable-gtk-doc, --disable-gtk-doc-html, --disable-doc, --disable-documentation, --with-xmlto, --with-fop, --disable-nls
.././configure: line 2300: config.log: No such file or directory
.././configure: line 2310: config.log: No such file or directory
cat: standard output: No such file or directory
make[3]: *** [package/pkg-generic.mk:240: /root/workspace/k230/k230_sdk/output/k230_canmv_defconfig/little/buildroot-ext/build/host-libffi-3.3/.stamp_configured] Error 1
make[2]: *** [Makefile:23: _all] Error 2
make[2]: Leaving directory '/root/workspace/k230/k230_sdk/output/k230_canmv_defconfig/little/buildroot-ext'
make[1]: *** [Makefile:69: all] Error 2
make[1]: Leaving directory '/root/workspace/k230/k230_sdk/src/little/buildroot-ext'
/bin/bash: line 2: exit: defconfig: numeric argument required

### Reproduction steps

 make CONF=k230_canmv_defconfig

### Hardware board

k230 evb board

**Comment by wangjianxin-canaan** [comment]
maby  permission denied  or   insufficient disk space?

**Comment by flightxgf** [comment]
thanks
