### ISSUE TITLE
Help! 环境配置报错

### ISSUE THREAD

**Issue by polamaxu** [kendryte/k230_sdk#3]
PC: ubuntu 20.04
按照教程步骤操作，到docker run -u root -it -v $(pwd):$(pwd) -v $(pwd)/toolchain:/opt/toolchain -w $(pwd) k230_sdk /bin/bash这一步报错Unable to find image 'k230_sdk:latest' locally
加了sudo，也没有用

### 报错图示
![2023-08-15-111231_744x479_scrot](https://github.com/kendryte/k230_sdk/assets/107613397/d124ac36-fda4-410b-bd34-b59a05709042)

![2023-08-15-112314_723x142_scrot](https://github.com/kendryte/k230_sdk/assets/107613397/63a6c997-3a53-4ff1-b1a4-15d65689828f)

### 文件夹如下：
![2023-08-15-111020_804x334_scrot](https://github.com/kendryte/k230_sdk/assets/107613397/a86a4c8e-a7d4-4359-b26e-2758ad6ce9b0)

请指教！谢谢！

**Comment by wuwentao** [comment]
命令默认的docker image domain，请使用：
```
`docker run -u root -it -v $(pwd):$(pwd) -v $(pwd)/toolchain:/opt/toolchain -w $(pwd) ghcr.io/kendryte/k230_sdk /bin/bash`
```
随后会同步更新到readme里面
@polamaxu

**Comment by wuwentao** [comment]
最新的文档已修复当前说明，关闭issue
