### ISSUE TITLE
[help]: Missing 'sysimage-sdcard.img' After Running 'make CONF=k230_canmv_defconfig’

### ISSUE THREAD

**Issue by zhanghb97** [kendryte/k230_sdk#30]
### Help

Hi!

I am attempting to run RVV code on the CanMV-K230-V1.0 board. I have followed the provided build process and executed the command `make CONF=k230_canmv_defconfig` to build the SDK. However, I am encountering an issue where the `sysimage-sdcard.img` is not being built in the images directory.

Below is the directory structure of the `k230_sdk/output/` after the build attempt:

```
.
└── k230_canmv_defconfig
    ├── big
    │   ├── mpp
    │   └── rt-smart
    ├── common
    │   ├── big-opensbi
    │   ├── cdk
    │   └── little-opensbi
    ├── images
    │   ├── big-core
    │   └── little-core
    └── little
        ├── buildroot-ext
        ├── linux
        └── uboot

```

Could you please advise if I have overlooked a step or if there is an additional process needed to generate the `sysimage-sdcard.img`?

Thanks in advance!

**Comment by negge** [comment]
I was able to successfully build the `sysimage-sdcard.img`. Can you post the output of your build log?

**Comment by zhanghb97** [comment]
@negge Thank you for checking this!

I reviewed the build log, and I found an issue with the `post-imege.sh` script:

```
>>>   Executing post-image script /home/zhanghongbin/k230_sdk/src/little/buildroot-ext/buildroot-9d1d4818c39d97ad7a1cdf6e075b9acae6dfff71/../board/canaan/k230/post-image.sh
/home/zhanghongbin/k230_sdk/output/k230_canmv_defconfig/little/buildroot-ext/host/bin/mkimage: Can't open /home/zhanghongbin/k230_sdk/output/k230_canmv_defconfig/little/buildroot-ext/images/Image: No such file or directory
cp: cannot stat '/home/zhanghongbin/k230_sdk/output/k230_canmv_defconfig/little/buildroot-ext/images/readme.txt': No such file or directory
cp: cannot stat '/home/zhanghongbin/k230_sdk/output/k230_canmv_defconfig/little/buildroot-ext/build/linux-custom/arch/riscv/boot/dts/thead/*.dtb': No such file or directory
cp: cannot stat '/home/zhanghongbin/k230_sdk/output/k230_canmv_defconfig/little/buildroot-ext/build/boot_ext4/light_mpw.dtb': No such file or directory
```

Have you ever encountered this problem? I will rebuild all things again to see if I can still reproduce the problem.

**Comment by zhanghb97** [comment]
I've found that when I employ the `-j` option in the command `make CONF=k230_canmv_defconfig` (for instance, `make CONF=k230_canmv_defconfig -j64`), it leads to the issue. If I compile the target using a single job in Makefile (without the `-j` option), the `sysimage-sdcard.img` is successfully created.

@negge Thanks again for the reply.

**Comment by wangjianxin-canaan** [comment]
Current  SDK does not support multi-process compilation, do not add multi-process compilation options like -j32
