### ISSUE TITLE
[other]: 您好 运行sample_audio音频例程的时候报缺页错误请问是什么情况

### ISSUE THREAD

**Issue by BluceGee** [kendryte/k230_sdk#36]
### Other

您好 运行sample_audio音频例程的时候报缺页错误请问是什么情况
![5ebd21aa118278f9f4742de65ad71b8](https://github.com/kendryte/k230_sdk/assets/67586614/e583b196-fc5f-4cfe-a9d5-fa6de550cbd2)

**Comment by gh-sxp** [comment]
您好，方便把您的com.wav文件上传一下吗？从日志看原因是您使用的wav文件音频采样精度8bit不支持导致的。可以尝试使用16/24bit的wave文件试一试。

**Comment by wuwentao** [comment]
当前issue超过几个月未收到反馈或回复，先直接close了，如后续仍有问题，可以reopen或继续反馈其他issue
