### ISSUE TITLE
[Bug]: DT says c910 but K230 is a c908

### ISSUE THREAD

**Issue by negge** [kendryte/k230_sdk#37]
### What happened

Reading the model infortmation from the device tree incorrectly reports the K230 as a c910

```
$ cat /sys/firmware/devicetree/base/model 
T-HEAD c910 ice
```

However the product page lists it as a c908 on https://www.canaan.io/product/k230

> The Kendryte K230 chip represents the latest generation SoC product in Canaan's ... Featuring a built-in dual core C908 CPU, with a frequency of up to 1.6GHz.

### Reproduction steps

Run `neofetch` or simply `cat /sys/firmware/devicetree/base/model`
![Screenshot at 2023-11-22 10-11-25](https://github.com/kendryte/k230_sdk/assets/280940/2b02a9b1-8afc-4ee2-adb1-a66a738c24c4)

### Hardware board

k230 evb board

**Comment by wangjianxin-canaan** [comment]
Thanks for the feedback, we will modify it in the later version。Gentoo linux running successfully on k230 ?

**Comment by negge** [comment]
> Gentoo linux running successfully on k230 ?

Yes, I replaced the rootfs with a stage3 from https://www.gentoo.org/downloads/#riscv

**Comment by wangjianxin-canaan** [comment]
The latest version has been modified.

**Comment by wuwentao** [comment]
fixed, if there is any new issue, please reopen or open new issue
