### ISSUE TITLE
[Bug]: 无法ssh登录

### ISSUE THREAD

**Issue by ycc688** [kendryte/k230_sdk#44]
### What happened

密码正确但是无法登录

### Reproduction steps

直接登录

### Hardware board

k230 canmv

### Bug frequency

必现

### Anything else

在/etc/ssh/sshd_config增加PermitRootLogin yes可解

**Comment by wangjianxin-canaan** [comment]
Thanks for the feedback, we will fix it in the later version

**Comment by wangjianxin-canaan** [comment]
最新版本已经修改

**Comment by ycc688** [comment]
收到
