### ISSUE TITLE
[Bug]: `gen_image_comm_func.sh` 的 `gen_version` 入参不对

### ISSUE THREAD

**Issue by tpoisonooo** [kendryte/k230_sdk#45]
### What happened

编译结束有个小错
![image](https://github.com/kendryte/k230_sdk/assets/7872421/05717d6a-0e42-4ab5-b760-581499ad092e)

看了下应该来自 `gen_version()`
![image](https://github.com/kendryte/k230_sdk/assets/7872421/0a93d625-75dd-4c12-be3f-0910bd150029)
在 docker 里访问 host 才存在的路径，应该改成相对路径。

### Reproduction steps

按 README，
STEP1.  在 docker 外  `make prepare_sourcecode`
STEP2.  进入 docker， `make CONF=k230_canmv_defconfig`

### Hardware board

k230 evb board

### Software version

commit-id  3ade2d07710fbbd5ab2e0919aa29298696873750

### Bug frequency

必现

**Comment by wangjianxin-canaan** [comment]
刚下载的sdk没有这个文件，报这个错误是正常情况，后面会重新初始化。
另外：export K230_SDK_ROOT := $(shell pwd) 变量是这样初始化的，理论上不应该存在路径问题，麻烦你看下是否还有问题。

```
local ver_file="etc/version/release_version"
local **post_copy_rootfs_dir**="${**K230_SDK_ROOT**}/board/common/post_copy_rootfs"
set +e; commitid=$(awk -F- '/^[^#]/ { print $6}' ${**post_copy_rootfs_dir**}/${ver_file});set -e;

**export K230_SDK_ROOT := $(shell pwd)**
```
