### ISSUE TITLE
[help]: k230 UART device questions

### ISSUE THREAD

**Issue by yf13** [kendryte/k230_sdk#46]
### Help

Can you please teach a few questions regarding k230 UART devices?

- What is the device clock frequency? `k230.dtsi` shows 50Mhz, is that is the  value for us to derive the baudrate divider number?
- Where can we find the register map for these UART devices? are they `ns16550` compliant? pointers to  SDK uboot or linux code base is fine.

**Comment by xiangbingj** [comment]
> ### Help
> Can you please teach a few questions regarding k230 UART devices?
> 
> * What is the device clock frequency? `k230.dtsi` shows 50Mhz, is that is the  value for us to derive the baudrate divider number?
> * Where can we find the register map for these UART devices? are they `ns16550` compliant? pointers to  SDK uboot or linux code base is fine.

Hi,

- The default frequency division clock of K230 uart is 50MHz. Of course, the upstream clock can also be configured. 
To understand the K230 clock tree, you can refer to this file：

> src/little/linux/arch/riscv/boot/dts/kendryte/clock_provider.dtsi

    Thank you for pointing this out.Next, we will support it after testing.

- Yes,K230 integrates DW uart ip,16550 Compatible Registers.

**Comment by yf13** [comment]
Thanks!
