### ISSUE TITLE
[help]: how to boot opensbi with test payload on CanMV-k230 board

### ISSUE THREAD

**Issue by yf13** [kendryte/k230_sdk#49]
### Help

how can we boot opensbi with its test payload on CanMV-k230 device? 

Here I can build out `fw_payload.elf` following little core opensbi make methods, but I don't know how to run it from within K230 u-boot console, can you please teach?

**Comment by LearnigF** [comment]
I think the jtag debugger would be a good solution to your problem

**Comment by wangjianxin-canaan** [comment]
你在uboot下 试下 boot_baremetal 命令 可以先把fw_payload.elf文件下载到内容，然后执行下类似下面命令  boot_baremetal  0   0x$fileaddr  0x$filesize；boot_baremetal 命令的详细使用方法如下

`
boot_baremetal 
 boot_baremetal cpu addr size
`

**Comment by yf13** [comment]
@wangjianxin-canaan  thanks a lot.
@LearnigF CanMV device doesn't support JTAG debugger. :(

**Comment by wangjianxin-canaan** [comment]
> canMV device doesn't support JTAG debugger.
canmv default disable jtag by u-boot, you can  enable jtag debuger ,and enable jtag  debugger patch is:

`
diff --git a/arch/riscv/dts/k230_canmv.dts b/arch/riscv/dts/k230_canmv.dts
index 5bd2e774..bf04f49a 100755
--- a/arch/riscv/dts/k230_canmv.dts
+++ b/arch/riscv/dts/k230_canmv.dts
@@ -234,9 +234,9 @@
                (IO4 ) ( 1<<SEL | 0<<SL | BANK_VOLTAGE_IO2_IO13 <<MSC | 0<<IE | 1<<OE | 0<<PU | 0<<PD | 4<<DS | 0<<ST )
 
                // JP1-PIN10 UART2
-               (IO5 ) ( 3<<SEL | 0<<SL | BANK_VOLTAGE_IO2_IO13 <<MSC | 1<<IE | 1<<OE | 0<<PU | 0<<PD | 4<<DS | 0<<ST )
+               (IO5 ) ( 1<<SEL | 0<<SL | BANK_VOLTAGE_IO2_IO13 <<MSC | 1<<IE | 0<<OE | 0<<PU | 0<<PD | 4<<DS | 0<<ST )
                // JP1-PIN11
-               (IO6 ) ( 3<<SEL | 0<<SL | BANK_VOLTAGE_IO2_IO13 <<MSC | 1<<IE | 1<<OE | 0<<PU | 0<<PD | 4<<DS | 0<<ST )
+               (IO6 ) ( 1<<SEL | 0<<SL | BANK_VOLTAGE_IO2_IO13 <<MSC | 1<<IE | 0<<OE | 1<<PU | 0<<PD | 4<<DS | 0<<ST )
 
                // JP1-PIN12 PWM2/3/4
                (IO7 ) ( 1<<SEL | 0<<SL | BANK_VOLTAGE_IO2_IO13 <<MSC | 1<<IE | 1<<OE | 0<<PU | 0<<PD | 7<<DS | 1<<ST )
`

**Comment by yf13** [comment]
@wangjianxin-canaan which pins on CanMV230 can be used for jtag?

**Comment by wangjianxin-canaan** [comment]
> @wangjianxin-canaan which pins on CanMV230 can be used for jtag?

uboot default disable cklink jtag,you can enable cklink jtag by modify follow code:

``` bash
    #src/little/uboot/arch/riscv/dts/k230_canmv.dts gpio5 and gipi6 modify
    (IO5 ) ( 1<<SEL | 0<<SL | BANK_VOLTAGE_IO2_IO13 <<MSC | 1<<IE | 0<<OE | 0<<PU | 0<<PD | 4<<DS | 0<<ST )
    (IO6 ) ( 1<<SEL | 0<<SL | BANK_VOLTAGE_IO2_IO13 <<MSC | 1<<IE | 0<<OE | 1<<PU | 0<<PD | 4<<DS | 0<<ST )
```

**Comment by LearnigF** [comment]
In fact I wonder why you don't want to use the uboot command to start opensbi。Without uboot, it means that ddr training can't be done and your code can only run on sram

**Comment by yf13** [comment]
@wangjianxin-canaan thank you!

I understand that with patched u-boot, we can connect CKLINK to pin `IO5 and IO6` on CanMV-K230 for JTAG debugging.
