### ISSUE TITLE
[help]: usb start too slow in CanMV-230 U-Boot 

### ISSUE THREAD

**Issue by yf13** [kendryte/k230_sdk#50]
### Help

For frequent tftp boot users, the current `usb start` command is too slow on CanMV-k230. Is there any way to improve it so that to save developers' life?

**Comment by xiangbingj** [comment]
> ### Help
> For frequent tftp boot users, the current `usb start` command is too slow on CanMV-k230. Is there any way to improve it so that to save developers' life?

Hi, uboot will scan two otg controller, you can disable otg0, so that you can quickly scan the usb-eth connected to otg1.
````
usbotg0: usb-otg@91500000 {
	compatible = "snps,dwc2";
	reg = <0x0 0x91500000 0x0 0x10000>;
	g-tx-fifo-size = <128 128 128 128 128 128>;
	dr_mode = "otg";
	otg-rev = <0x200>;
	u-boot,dm-pre-reloc;
	status = "disabled";
};
````

**Comment by yf13** [comment]
@xiangbingj thanks a lot. this works!
