### ISSUE TITLE
[help]: How to use HDMI output in Linux with Big Core of CanMV

### ISSUE THREAD

**Issue by troibe** [kendryte/k230_sdk#52]
### Help

I'm trying use the HDMI output to display 3D graphics which are computed on the big core.
My setup is currently running buidroot [linux on the big core](https://www.remlab.net/op/k230-canmv-debian.shtml).

Now I have a couple of questions for the CanMV board:
- First of all is the HDMI output physically connected to both the small and the big core?
- Does the CanaanDRM driver work with both cores?

The only document I could find so far is [this](https://github.com/kendryte/k230_docs/blob/main/zh/01_software/board/osdrv/K230_DRM_API%E5%8F%82%E8%80%83.md).
For this document I have the following questions:
- Is `DSI-1` connected to the HDMI port or the DSI connector on the board?
- If I run `modetest` the `DSI-1` always shows up as connected even if there is no DSI or HDMI screen connected. Is this right?

Background:
I have added Vector extension support to SwiftShader (a graphics driver for CPUs).
Currently I have a working setup in qemu using buildroot that I want to try on real hardware.

**Comment by zhangxiaojingCAN** [comment]
Hi,
K230 chip only has MIPI DSI interface. On CanMV-K230 board, we use a MIPI-TO-HDMI chip that converts MIPI signal to HDMI video. The MIPI-TO-HDMI chip is controlled by I2C interface. 
As you know, in current SDK, big C908 core runs a RTOS and little C908 core runs linux. Both cores can controlled any device like external MIPI-TO-HDMI chip or VO/DSI module of K230 chip. However, in current SDK, HDMI/DSI/VO is only initialized on big C908 core running RTOS. Though little C908 core supports DRM driver, it just controls several graphics layers of VO. In another word, the DRM dirver in linux is not a full version. If you just run a linux on big core, existing DRM driver doesn't initialize  full hardware for HDMI output.
We're implementing the full functional DRM driver for linux. It would be released in couple of weeks. By then, you can use HDMI output in a linux. We will also release Ubuntu and Debian image.
HDMI output is controlled by a MIPI-to-HDMI chip

**Comment by troibe** [comment]
Did you already make any progress on this issue?
For now I resorted to rendering to a virtual framebuffer using `Xvfb`.
The performance is really promising (close to 2x the framerate compared to scalar execution).
So of course it would be nice to have a visual demo using a real framebuffer.

**Comment by intx82** [comment]
any news?

**Comment by zhangxiaojingCAN** [comment]
Linux DRM dirver was released in linux SDK https://github.com/kendryte/k230_linux_sdk
