### ISSUE TITLE
[help]: Is ocr onnx model released?

### ISSUE THREAD

**Issue by Basicname** [kendryte/k230_sdk#56]
### Help

Thanks your awesome work
But I can only find int16 quantized kmodels in the sdk,so I wonder if the source onnx(or other format) model is released? Where can I get it?
Thanks in advance.

**Comment by zhaixingang** [comment]
we focus on K230 applications, so no onnx will be released, only kmodel.

**Comment by zhaixingang** [comment]
> ### Help
> Thanks your awesome work But I can only find int16 quantized kmodels in the sdk,so I wonder if the source onnx(or other format) model is released? Where can I get it? Thanks in advance.
we focus on K230 applications, so no onnx will be released, only kmodel.

**Comment by curioyang** [comment]
> ### Help
> Thanks your awesome work But I can only find int16 quantized kmodels in the sdk,so I wonder if the source onnx(or other format) model is released? Where can I get it? Thanks in advance.

Maybe you'd better to train OCR model by yourself, or get it in other way.

**Comment by Basicname** [comment]
> > ### Help
> > Thanks your awesome work But I can only find int16 quantized kmodels in the sdk,so I wonder if the source onnx(or other format) model is released? Where can I get it? Thanks in advance.
> 
> Maybe you'd better to train OCR model by yourself, or get it in other way.

Thank you. I'll try it.
