### ISSUE TITLE
[Feature]: 是否会考虑增加一个内部合封DDR/LPDDR的型号？

### ISSUE THREAD

**Issue by Ivan-Xie2018** [kendryte/k230_sdk#62]
### Feature description

是否会考虑增加一个内部合封DDR/LPDDR的型号？这样芯片封装可以采用QFN-128而不需要BGA了。同时希望提供基于RTOS的SDK版本，方便做低功耗嵌入式视觉和HMI应用

**Comment by zhangxiaojingCAN** [comment]
目前已经有合封LPDDR4 128MB的芯片型号K230D，封装依然是BGA，有需要可以考虑。更多形式封装目前尚无确定性计划，跟后续芯片的演进形态和商业需求关系较大。如果您有大规模商业项目需求可以和销售联系。
目前SDK为RTOS+LINUX，如果不需要linux可以只运行大核CPU跑RTOS。更为完善的RTOS only SDK版本正在开发之中，预计5月底会github开源发布。
