### ISSUE TITLE
[help]: docker build error

### ISSUE THREAD

**Issue by mrfsc** [kendryte/k230_sdk#66]
### Help

when i build k230_sdk docker docker image with: **docker build -f tools/docker/Dockerfile -t k230_docker tools/docker** , it returns: **Sending build context to Docker daemon  6.144kB
Step 1/28 : FROM ubuntu:20.04
20.04: Pulling from library/ubuntu
9ea8908f4765: Retrying in 10 seconds
error pulling image configuration: download failed after attempts=6: dial tcp 47.88.58.234:443: connect: connection refused**.
it seems that pulling image over time, how can i fix this?

**Comment by wuwentao** [comment]
Step 1/28 : FROM ubuntu:20.04

you PC can't access docker hub network for this base OS, the error msg is  network error 

solution:
1. use a dockerhub mirror for this base OS
2. fix your network connection issue to default dockerhub and fix network connection issue
3. can't fix network and can't know how to add mirror, but you can access github, so you can directly pull github docker image and not build from src, just refer to README.

**Comment by kamejoko80** [comment]
After calling the build command: docker build -f tools/docker/Dockerfile -t k230_docker tools/docker, it's stuck at the below lines:

--2025-03-14 12:22:20--  https://ai.b-bug.org/k230/downloads/aitest/aitest-0.0.6.dev20240829-py3-none-any.whl
Resolving ai.b-bug.org (ai.b-bug.org)... 125.235.4.59
Connecting to ai.b-bug.org (ai.b-bug.org)|125.235.4.59|:443...

Link is dead, do you have any update?
