### ISSUE TITLE
[other]: 这个芯片能商用开发产品吗？官网找不到代理

### ISSUE THREAD

**Issue by xianyo** [kendryte/k230_sdk#67]
### Other

芯片挺好的，这个芯片是否能商用开发产品？
官网发邮件没响应？有没有代理？芯片在哪里买都不知道。

难道只理会大客户？

**Comment by huangzhenming** [comment]
芯片样品购买您可以去[立创商城](https://so.szlcsc.com/global.html?k=canaan)搜索 canaan， [或者在taobao网搜索K230芯片样片即可。](https://item.taobao.com/item.htm?id=760897299480)

其它商务合作信息可写上您的需求，发邮件至 [SalesAI](mailto:salesai@canaan-creative.com)
