### ISSUE TITLE
[help]: 关于AHD四通道输入支持

### ISSUE THREAD

**Issue by xianyo** [kendryte/k230_sdk#70]
### Help

1、sensor里面支持了AHD RX芯片xs9922b，K230是否支持MIPI CSI虚拟通道呢？能够同时接收显示四通道的视频数据？

2、四通道AHD视频数据是否可以同时在屏上四分割缩放显示？
      四分割同时显示视频数据，要放四个vo layer?
      只有一个vo layer支持缩放，是不是可以在VI那边先处理缩放好，然后再给到VO？
      如果只需显示单个通道数据，VI那边停止缩放，直接显示在全屏的layer，这样是否可行？
      如果LCD是竖屏横用转了90度，把视频数据显示在屏上是否也要跟着转90度呢？

**Comment by zhaoshuaiadada** [comment]
1. 支持MIPI CSI虚拟通道、但是4路数据进来没有办法做输出，目前只能一路进来然后在出去。
2. vi 不支持缩放、得用其他的模块做

**Comment by xianyo** [comment]
其它那哪个模块呢？上面说的两路缩放后显示，是支持的吧？

**Comment by xianyo** [comment]
> 1. 支持MIPI CSI虚拟通道、但是4路数据进来没有办法做输出，目前只能一路进来然后在出去。
> 2. vi 不支持缩放、得用其他的模块做

支持MIPI CSI虚拟通道、但是4路数据进来没有办法做输出，目前只能一路进来然后在出去。    


这个是硬件限制还是软件目前不支持呢？
