### ISSUE TITLE
[help]: There are no pre-built ubuntu/debian images available for the CanMV-k230-LP4 3.0 AI board

### ISSUE THREAD

**Issue by DingliZhang** [kendryte/k230_sdk#74]
### Help

https://kendryte-download.canaan-creative.com/developer/k230/CanMV-K230_debian_sdcard_sdk_1.3.img.gz
https://kendryte-download.canaan-creative.com/developer/k230/CanMV-K230_ubuntu_sdcard_1.3.img.gz
The above two images don't seem to work on CanMV-k230-LP4 3.0, are there any official ubuntu/debian images available?

I see that there is documentation on it:
https://developer.canaan-creative.com/k230/dev/zh/03_other/K230_debian_ubuntu%E8%AF%B4%E6%98%8E.html
Is it applicable to CanMV-k230-LP4 3.0?
Thanks!

**Comment by wangjianxin-canaan** [comment]
> ve two images don't seem to work on CanMV-k230-LP4 3.0, are there any official ubuntu/debian images available?
The above two images  can not work on CanMV-k230-LP4 3.0.There is no official mirror yet.

**Comment by wangjianxin-canaan** [comment]
> I see that there is documentation on it:
> https://developer.canaan-creative.com/k230/dev/zh/03_other/K230_debian_ubuntu%E8%AF%B4%E6%98%8E.html
> Is it applicable to CanMV-k230-LP4 3.0?
 applicable to CanMV-k230-LP4 3.0,but The current  sdk doesn't support CanMV-k230-LP4 3.0 boards ,next version  will support CanMV-k230-LP4 3.0.

**Comment by DingliZhang** [comment]
> > I see that there is documentation on it:
> > https://developer.canaan-creative.com/k230/dev/zh/03_other/K230_debian_ubuntu%E8%AF%B4%E6%98%8E.html
> > Is it applicable to CanMV-k230-LP4 3.0?
> > applicable to CanMV-k230-LP4 3.0,but The current  sdk doesn't support CanMV-k230-LP4 3.0 boards ,next version  will support CanMV-k230-LP4 3.0.

Understood. Thank you for your prompt reply.

**Comment by DingliZhang** [comment]
@wuwentao I saw that v1.8.0 of the SDK was released. 
Could you provide Ubuntu/Debian pre-built images or documentation for CanMV-k230-LP4 3.0?
Thanks a lot!

**Comment by DingliZhang** [comment]
Hi @wangjianxin-canaan 
Any update? Thanks a lot.

**Comment by wangjianxin-canaan** [comment]
> @wuwentao I saw that v1.8.0 of the SDK was released. Could you provide Ubuntu/Debian pre-built images or documentation for CanMV-k230-LP4 3.0? Thanks a lot!

CanMV-k230-LP4 3.0 debian and ubuntu images:
https://kvftsfijpo.feishu.cn/drive/folder/SbBZfsyA5lii4hdcu2lciP9onVf?from=from_copylink

and this image is build by https://github.com/kendryte/k230_linux_sdk ,linux kernel is 6.6.36.

**Comment by DingliZhang** [comment]
> > @wuwentao I saw that v1.8.0 of the SDK was released. Could you provide Ubuntu/Debian pre-built images or documentation for CanMV-k230-LP4 3.0? Thanks a lot!
> 
> CanMV-k230-LP4 3.0 debian and ubuntu images: https://kvftsfijpo.feishu.cn/drive/folder/SbBZfsyA5lii4hdcu2lciP9onVf?from=from_copylink
> 
> and this image is build by https://github.com/kendryte/k230_linux_sdk ,linux kernel is 6.6.36.

Thanks a lot!

**Comment by peachtop98** [comment]
> > [@wuwentao](https://github.com/wuwentao) I saw that v1.8.0 of the SDK was released. Could you provide Ubuntu/Debian pre-built images or documentation for CanMV-k230-LP4 3.0? Thanks a lot!我看到 SDK 的 v1.8.0 发布了。您能否提供 CanMV-k230-LP4 3.0 的 Ubuntu/Debian 预构建映像或文档？多谢！
> 
> CanMV-k230-LP4 3.0 debian and ubuntu images:CanMV-k230-LP4 3.0 debian 和 ubuntu 镜像： https://kvftsfijpo.feishu.cn/drive/folder/SbBZfsyA5lii4hdcu2lciP9onVf?from=from_copylink
> 
> and this image is build by https://github.com/kendryte/k230_linux_sdk ,linux kernel is 6.6.36.而这个镜像是用 https://github.com/kendryte/k230_linux_sdk 构建的，linux 内核是 6.6.36。

请问这个镜像的k230 login以及password是多少呢

**Comment by wangjianxin-canaan** [comment]
> > > [@wuwentao](https://github.com/wuwentao) I saw that v1.8.0 of the SDK was released. Could you provide Ubuntu/Debian pre-built images or documentation for CanMV-k230-LP4 3.0? Thanks a lot!我看到 SDK 的 v1.8.0 发布了。您能否提供 CanMV-k230-LP4 3.0 的 Ubuntu/Debian 预构建映像或文档？多谢！
> > 
> > 
> > CanMV-k230-LP4 3.0 debian and ubuntu images:CanMV-k230-LP4 3.0 debian 和 ubuntu 镜像： https://kvftsfijpo.feishu.cn/drive/folder/SbBZfsyA5lii4hdcu2lciP9onVf?from=from_copylink
> > and this image is build by https://github.com/kendryte/k230_linux_sdk ,linux kernel is 6.6.36.而这个镜像是用 https://github.com/kendryte/k230_linux_sdk 构建的，linux 内核是 6.6.36。
> 
> 请问这个镜像的k230 login以及password是多少呢

root root 
用户密码可以从这个文件看出来：
https://github.com/kendryte/k230_linux_sdk/blob/dev/buildroot-overlay/board/canaan/k230-soc/distribution.sh
