### ISSUE TITLE
[help]: 关于电源和功耗的几个问题

### ISSUE THREAD

**Issue by Qinka** [kendryte/k230_sdk#8]
### Help

1. 我看 datasheet 里面提到了 Power control module 的几个电源策略，比如像 sleep0 sleep1 standby 啥的，这个要如何配置使用呢呢？
2. 这个 Power control module 和 power management unit 是一个东西么？
3. https://github.com/kendryte/k230_docs/issues/6#issuecomment-1709539722 这个里面提到的 CPU0 和 CPU1 的电源问题中， CPU1 单独上下电的功能大概什么能有？
4. PMU 这个支持唤醒和休眠么？要怎么操作呢？大小核的系统是否可以分别唤起和休眠呢？
5. 当前如何能获取当前 CPU、KPU、DPU 等设备的当前实际的主频和功耗呢？
6. 如何能详细的控制SOC上各个部份的电源，以尽可能的减小功耗呢？
7. 目前除了上述手段，由还有哪写方法能够降低功耗？能保证需要运行 AI 的时候，能够快速执行，然后其他的时候，能够以最低功耗待机啥的。

**Comment by wycwyhwyq** [comment]
1. sleep, standby mode 用户层目前还未支持
2. 不是，Power control module主要是管理片内各模块的上下电，power management unit主要是配合外部PMIC管理整个SOC的上下电。
3. 后续版本会支持
4. PMU只支持整个SOC上下电，具体操作请参考[PMU使用说明](https://github.com/kendryte/k230_docs/blob/main/zh/01_software/board/osdrv/K230_PMU_%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97.md)
5. 请参考[PM模块使用说明](https://github.com/kendryte/k230_docs/blob/main/zh/01_software/board/mpp/K230_PM%E6%A1%86%E6%9E%B6%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97.md)
6. 请问您的使用场景是什么，如果有实际产品要求可联系FAE做定制化

**Comment by chenhb3** [comment]
由于超7天未继续反馈结果或情况，问题先关闭，后续若有需要和重新打开或创建，谢谢！
