### ISSUE TITLE
[help]:  小核 linux cpu_freq 如何配置

### ISSUE THREAD

**Issue by Qinka** [kendryte/k230_sdk#9]
### Help

根据 **K230\_功耗管理适配指南**  里面提及的 小核 linux cpu_freq 的功能，找不到 `/sys/devices/system/cpu/cpu0/cpufreq` 这个目录以及下面对应的控制的东西。

**Comment by wycwyhwyq** [comment]
小核linux cpu_freq目前还未支持

**Comment by chenhb3** [comment]
问题将先关闭，感谢您的关注；后续若有问题，请重新创建或打开，谢谢！
